# {{- $root := . }}
# {{- if $root.Values.FargateProfile.enabled }}
# {{- range $root.Values.FargateProfile.items }}
# ---
# apiVersion: eks.aws.crossplane.io/v1beta1
# kind: FargateProfile
# metadata:
#   name: {{ include "common-gitops.names.name" $root }}-{{ .name }}-cluster
#   labels:
#     {{- include "common-gitops.aws.labels" $root | trim | nindent 4 }}
#     {{- with merge (($root.Values.FargateProfile).labels) (.labels) }}
#     {{- include "common-gitops.tplvalues.render" (dict "value" . "context" $root) | nindent 4 }}
#     {{- end }}
# spec:
#   {{- with .deletionPolicy }}
#   deletionPolicy: {{ . }}
#   {{- end }}
#   forProvider:
#     clusterNameRef:
#       name: sample-cluster
#     podExecutionRoleArnRef:
#       name: somerole
#     selectors:
#     - namespace: default
#     {{- with ($root.Values.global).awsRegion }}
#     region: {{ . | quote }}
#     {{- else }}
#       {{- with (.forProvider).region }}
#     region: {{ . | quote }}
#       {{- else }}
#     region: us-west-2
#       {{- end }}
#     {{- end }}
#     tags:
#     {{- include "common-gitops.aws.tags" $root | trim | nindent 6 }}
#     {{- range .tags }}
#       - key: {{ .key | quote }}
#         value: {{ .value | quote }}
#     {{- end }}
#   {{- include "common-gitops.aws.publishConnectionDetailsTo" $root | nindent 2 }}
#   {{- include "common-gitops.aws.providerConfigRef" $root | nindent 2 }}
# {{- end }}
# {{- end }}
