default_stages: [commit]
repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
        exclude: .*/templates/|^tests|^to-be-deleted/
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude_types: [svg]
