---
## AWS S3 bucket resources configurations
##############
# Global
##############
# global:
#   chartNameOverride: "infra"

#   releaseNameOverride: "infra"

#   tags: {}
  # tags:
  #   - key: k1
  #     value: v1

  # labels: {}

  # Annotations to be added to the published metadata secret
  # annotations: {}

  # aws provider configmap
  # providerConfigRef:
  #   name: aws-provider-cicd

Bucket:
  enabled: true
  items:
    test-bucket:
      deletionPolicy: Delete
      annotations:
        # This will be the actual bucket name. It must be globally unique, so you
        # probably want to change it before trying to apply this example.
        crossplane.io/external-name: lt-test-bucket-22
      forProvider:
        acl: private
        locationConstraint: us-east-1
        publicAccessBlockConfiguration:
          blockPublicPolicy: true
        accelerateConfiguration:
          status: Enabled
        versioningConfiguration:
          status: Enabled
        tagging:
          tagSet:
            - key: key1
              value: val1
            - key: secondKey
              value: val2
            - key: key3
              value: val3
        objectLockEnabledForBucket: false
        serverSideEncryptionConfiguration:
          rules:
            - applyServerSideEncryptionByDefault:
                sseAlgorithm: AES256
        corsConfiguration:
          corsRules:
            - allowedMethods:
                - "GET"
              allowedOrigins:
                - "*"
              allowedHeaders:
                - "*"
              exposeHeaders:
                - "x-amz-server-side-encryption"
        lifecycleConfiguration:
          rules:
            - status: Enabled
              filter:
                prefix: "ola/"
              expiration:
                days: 15
        replicationConfiguration:
          roleRef:
            name: somerole
          rules:
            - destination:
                storageClass: STANDARD
                bucketRef:
                  name: repl-dest
              deleteMarkerReplication:
                status: Disabled
              filter:
                prefix: ""
              priority: 0
              id: rule-1
              status: Enabled
BucketPolicy:
  enabled: true
  items:
    test-bucket-policy:
      deletionPolicy: Delete
      forProvider:
        region: us-east-1
        bucketNameRef:
          name: test-bucket
        policy:
          version: '2012-10-17'
          statements:
            - action:
                - s3:ListBucket
                - s3:GetBucketLocation
                - s3:ListBucketMultipartUploads
                - s3:PutBucketCORS
              effect: Allow
              principal:
                awsPrincipals:
                  - iamUserArnSelector:
                      matchLabels:
                        example: "true"
              resource:
                # This is unfortunately not currently able to be inferred from a
                # reference to test-bucket, and must therefore be set to the ARN of
                # test-bucket (i.e. its actual external name).
                - "arn:aws:s3:::crossplane-example-bucket"
              condition:
              - operatorKey: StringEquals
                conditions:
                  - key: "aws:Key1"
                    stringValue: "value1"
                  - key: "aws:Key2"
                    stringValue: "value2"
              - operatorKey: IpAddress
                conditions:
                  - key: "aws:SourceIp"
                    stringValue: "192.0.2.0/24"
              - operatorKey: NotIpAddress
                conditions:
                  - key: "aws:SourceIp"
                    stringValue: "192.0.2.188/32"
