# Ref: https://github.com/bitnami/charts/blob/main/.github/workflows/assign-asset-label.yml
name: '[Support] Assign asset label'
on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - ready_for_review
permissions:
  pull-requests: write
  issues: write
jobs:
  assign-label:
    name: Assign label
    runs-on: ubuntu-latest
    steps:
      - name: Install readme-generator-for-helm
        run: npm install -g @bitnami/readme-generator-for-helm@2.4.3
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0
          persist-credentials: true
      - name: Get list of changed directories
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          dir_names: "true"
          files: |
            charts/**
      - id: get-asset
        name: Get modified assets
        run: |
          # Adding || true to avoid "Process exited with code 1" errors
          assets=($(echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr ' ' '\n' | grep -e '^charts\/shared\/.*' | sed -nr "s|charts/shared/([^/]*).*|\1|p" | uniq | sort || true))
          assets+=($(echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr ' ' '\n' | grep -e '^charts\/iac\/.*' | sed -nr "s|charts/iac/([^/]*).*|\1|p" | uniq | sort || true))
          assets+=($(echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr ' ' '\n' | grep -e '^charts\/modules\/apps\/.*' | sed -nr "s|charts/modules/apps/([^/]*).*|\1|p" | uniq | sort || true))
          assets+=($(echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr ' ' '\n' | grep -e '^charts\/modules\/iac\/.*' | sed -nr "s|charts/modules/iac/([^/]*).*|\1|p" | uniq | sort || true))
          if [[ "${#assets[@]}" -ne "0" ]]; then
            echo "result=ok" >> $GITHUB_OUTPUT
            echo "message=Adding label '${assets[@]}'" >> $GITHUB_OUTPUT
            echo "name=$(echo ${assets[@]}|tr ' ' ', ')" >> $GITHUB_OUTPUT
          else
            echo "result=skip" >> $GITHUB_OUTPUT
            echo "message=No label matches" >> $GITHUB_OUTPUT
            echo "name=NONE" >> $GITHUB_OUTPUT
          fi
      - name: Show messages
        uses: actions/github-script@v6
        with:
          script: |
            if ("${{ steps.get-asset.outputs.result }}" != "ok" ) {
              core.warning("${{ steps.get-asset.outputs.message }}")
            } else {
              core.info("${{ steps.get-asset.outputs.message }}")
            }
      - name: Labeling
        if: ${{ steps.get-asset.outputs.result == 'ok' }}
        uses: fmulero/labeler@1.0.5
        with:
          add-labels: "${{ steps.get-asset.outputs.name }}"
