# Ref: https://github.com/bitnami/charts/blob/main/.github/workflows/generate-chart-readme.yml
name: '[HELM] Update README'
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - ready_for_review
    paths:
      - 'charts/**/values.yaml'
permissions:
  contents: write
  pull-requests: read
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.SOFTWARE_APP_ID }}
          private_key: ${{ secrets.SOFTWARE_APP_PRIVATE_KEY }}
          installation_id: ${{ secrets.SOFTWARE_APP_INSTALLATION_ID }}
      - name: Install readme-generator-for-helm
        run: npm install -g @bitnami/readme-generator-for-helm@2.4.3
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0
          persist-credentials: true
          path: luminartech/helm-charts-public
          token: ${{ steps.generate_token.outputs.token }}
      - name: Get list of changed directories
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          dir_names: "true"
          path: luminartech/helm-charts-public
          files: |
            charts/**
      - name: Execute readme-generator-for-helm
        run: |
          set -x
          cd luminartech/helm-charts-public
          # Adding || true to avoid "Process exited with code 1" errors
          charts_dirs_changed=($(echo "${{ steps.changed-files.outputs.all_changed_files}}" | tr ' ' '\n' | grep -e '^charts\/iac\/.*/' | sed -nr "s|charts/iac/([^/]*).*|charts/iac/\1|p" | sort | uniq || true))
          charts_dirs_changed+=($(echo "${{ steps.changed-files.outputs.all_changed_files}}" | tr ' ' '\n' | grep -e '^charts\/shared\/.*/' | sed -nr "s|charts/shared/([^/]*).*|charts/shared/\1|p" | uniq || true))
          charts_dirs_changed+=($(echo "${{ steps.changed-files.outputs.all_changed_files}}" | tr ' ' '\n' | grep -e '^charts\/modules\/apps\/.*/' | sed -nr "s|charts/modules/apps/([^/]*).*|charts/modules/apps/\1|p" | sort | uniq || true))
          charts_dirs_changed+=($(echo "${{ steps.changed-files.outputs.all_changed_files}}" | tr ' ' '\n' | grep -e '^charts\/modules\/iac\/.*/' | sed -nr "s|charts/modules/iac/([^/]*).*|charts/modules/iac/\1|p" | sort | uniq || true))
          echo $charts_dirs_changed
          for chart in "${charts_dirs_changed[@]}"; do
            echo "Updating README.md for ${chart}"
            if [ -f "${chart}/values.yaml" ]; then
              readme-generator --values "${chart}/values.yaml" --readme "${chart}/README.md" --schema "/tmp/schema.json"
            fi
          done
      - name: Push changes to PR branch
        run: |
          # Push all the changes
          cd luminartech/helm-charts-public
          if git status -s | grep charts; then
            git config user.name "CI Bot"
            git config user.email "sre@luminartech.com"
            git add . && git commit -am "Update README.md with readme-generator-for-helm" --signoff && git push
          fi
