# Ref: https://github.com/bitnami/charts/blob/main/.github/workflows/generate-chart-readme.yml
name: '[HELM] Package and release'
on:
  push:
    branches:
      - main
    paths:
      - 'charts/*/**.yaml'
      - 'charts/*/**.tpl'
      - 'charts/*/**.txt'
permissions:
  contents: write
jobs:
  package-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Install readme-generator-for-helm
        run: npm install -g @bitnami/readme-generator-for-helm@2.4.2
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          installation_id: ${{ secrets.APP_INSTALLATION_ID }}
      - name: Use token
        env:
          TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          echo "The generated token is masked: ${TOKEN}"
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}
          token: ${{ secrets.TOKEN }}
          path: ${{ github.repository }}
      - name: Helm Installation
        uses: azure/setup-helm@v3
        with:
          version: v3.10.3
      - name: Helm Repository Checkout
        uses: actions/checkout@v2
        with:
          repository: luminartech/helm-repo-public
          token: ${{ secrets.TOKEN }}
          fetch-depth: 0
          persist-credentials: true
          ref: main
          path: ${{ github.repository.owner }}/helm-repo-public
      - name: Build helm package and add to releases
        run: |
          set -x
          git config user.name "CI Bot"
          git config user.email "sre@luminartech.com"
          # Using the Github API to detect the files changed as git merge-base stops working when the branch is behind
          # and jitterbit/get-changed-files does not support pull_request_target
          URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
          files_changed_data=$(curl -s --header 'authorization: Bearer ${{ secrets.TOKEN }}' -X GET -G "$URL")
          echo ${files_changed_data}
          files_changed="$(echo $files_changed_data | jq -r '.[] | .filename')"
          # Adding || true to avoid "Process exited with code 1" errors
          charts_dirs_changed="$(echo "$files_changed" | xargs dirname | grep -o "charts/[^/]*" | sort | uniq || true)"
          cd ${{ github.repository }}
          for chart in ${charts_dirs_changed}; do
            cd ${chart}
            echo "Generating helm package for ${chart}"
            helm dependency update
            rm -f *.tgz || true
            helm package .
            chart_name=$(awk -F '[/]' '{print $2}' <<< ${chart})
            chart_version=$(ls -t|grep -e '.*-.*\..*\.tgz'|sed 's/.tgz//'|awk -F '[-]' '{print $NF}')
            # this command should fail the job if tag already exists
            git tag ${chart_name}-${chart_version}
            git push -f origin ${chart_name}-${chart_version}
            # Do not force update, we want it to fail if same version package exists
            mv *.tgz "${{ github.repository.owner }}/helm-repo-public/"
            cd -
          done
      - name: Push changes to helm repository
        run: |
          set -x
          # Push all the changes
          cd ${{ github.repository.owner }}/helm-repo-public
          git status
          if git status -s | grep -e '.*-.*\..*\.tgz'; then
            git config user.name "CI Bot"
            git config user.email "sre@luminartech.com"
            git add *.tgz
            git status
            git commit -am "[ CI Bot ] Generated helm packages" --signoff
            git push
          fi
